name: "Analysis"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  analyze:
    name: Analyze
    runs-on: windows-latest
    permissions:
      contents: read
      security-events: write
      
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.x
          8.x

    - name: Run .NET Code Analysis
      uses: dotnet/code-analysis@main
      id: code-analysis
      with:
        project: ClickHouse.Client\ClickHouse.Client.csproj
        build-breaking: false
        all-categories: all

    - name: Upload analysis results to GitHub
      uses: github/codeql-action/upload-sarif@v2
      with:
        path: ${{ steps.code-analysis.outputs.sarifFile }}
        wait-for-processing: true

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework: ["net462", "net48", "netstandard2.1", "net8.0"]
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test ClickHouse.Client.Tests/ClickHouse.Client.Tests.csproj --framework ${{ matrix.framework }}

