name: Benchmark

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**/*.md'
  pull_request:
    branches: [ main ]

jobs:
  benchmark:
    name: Short
    runs-on: ubuntu-latest
    services:
      clickhouse:
        image: clickhouse/clickhouse-server:latest
        ports:
          - 8123:8123

    steps:
    - uses: actions/checkout@v4
      name: Checkout
    
    - uses: actions/cache@v4
      name: Cache NuGet
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.x
          7.x

    - name: Run
      run: dotnet run --project ClickHouse.Client.Benchmark/ClickHouse.Client.Benchmark.csproj --framework net6.0 --configuration Release -- --join --filter "*" --artifacts . --job Short
      env:
        CLICKHOUSE_CONNECTION: Host=localhost;Port=8123

    - name: Post results to summary
      run: cat results/*-report-github.md >> $GITHUB_STEP_SUMMARY
