name: Integration Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**/*.md'
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    services:
      clickhouse:
        image: clickhouse/clickhouse-server:latest
        ports:
          - 8123:8123
          
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - uses: actions/cache@v4
      name: Cache NuGet
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          3.1.x
          6.x
          8.x
          
    - name: Install GitHubActionsTestLogger
      run: dotnet add ClickHouse.Client.IntegrationTests/ClickHouse.Client.IntegrationTests.csproj package GitHubActionsTestLogger --no-restore

    - name: Test with coverage
      run: dotnet test --framework net8.0 --configuration Release --verbosity normal --logger GitHubActions  /clp:ErrorsOnly /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:SkipAutoProps=true
      env:
        CLICKHOUSE_CONNECTION: Host=localhost;Port=8123
        CLICKHOUSE_VERSION: latest
