name: Regression

on:
  push:
    branches: [ master ]
    paths-ignore:
    - '**/*.md'
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Regression
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
        - 'yandex/clickhouse-server:19.11.2.7'
        - 'yandex/clickhouse-server:20.3.18.10'
        - 'yandex/clickhouse-server:21.5.5.12'
    services:
      clickhouse:
        image: ${{ matrix.tag }}
        ports:
          - 8123:8123
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --framework netcoreapp2.2 --configuration Release --no-restore ClickHouse.Client/ClickHouse.Client.csproj
    - name: Test
      run: dotnet test --framework netcoreapp3.1 --configuration Release --no-restore --verbosity normal
      env:
        CLICKHOUSE_CONNECTION: Host=localhost;Port=8123
