name: Regression

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        clickhouse-version: [19.11.2.7, 20.3.18.10, latest]
    services:
      clickhouse:
        image: yandex/clickhouse-server:${{matrix.clickhouse-version}}
        ports:
          - 8123:8123
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --framework netcoreapp2.2 --configuration Release --no-restore ClickHouse.Client/ClickHouse.Client.csproj
    - name: Test
      run: dotnet test --framework netcoreapp3.0 --configuration Release --no-restore --verbosity normal
      env:
        CLICKHOUSE_CONNECTION: Host=localhost;Port=8123
