name: Regress

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**/*.md'

jobs:
  regress-dotnet:
    name: .NET version
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        framework: ['net6.0', 'net5.0', 'netcoreapp3.1']

    services:
      clickhouse:
        image: clickhouse/clickhouse-server:latest
        ports:
          - 8123:8123
    steps:
    - uses: actions/checkout@v4
      name: Checkout
    
    - uses: actions/cache@v3
      name: Cache NuGet
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          3.1.x
          5.x
          6.x

    - name: Install GitHubActionsTestLogger
      run: dotnet add ClickHouse.Client.Tests/ClickHouse.Client.Tests.csproj package GitHubActionsTestLogger --no-restore

    - name: Test
      run: dotnet test --framework ${{ matrix.framework }} --configuration Release --verbosity normal --logger GitHubActions /clp:ErrorsOnly
      env:
        CLICKHOUSE_CONNECTION: Host=localhost;Port=8123

  regress:
    name: ClickHouse
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
        - '21.3'
        - '21.8'
        - '22.3'
        - '22.8'
        - '22.9'
        - '22.12'
        - '23.3'
        - '23.6'
        - '23.8'
        - '23.9'

    services:
      clickhouse:
        image: "clickhouse/clickhouse-server:${{ matrix.tag }}"
        ports:
          - 8123:8123

    steps:
    - uses: actions/checkout@v4
      name: Checkout

    - uses: actions/cache@v3
      name: Cache NuGet
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.x

    - name: Install GitHubActionsTestLogger
      run: dotnet add ClickHouse.Client.Tests/ClickHouse.Client.Tests.csproj package GitHubActionsTestLogger --no-restore

    - name: Test
      run: dotnet test --framework net6.0 --configuration Release --verbosity normal --logger GitHubActions
      env:
        CLICKHOUSE_CONNECTION: Host=localhost;Port=8123
        CLICKHOUSE_CONTAINER_VERSION: ${{ matrix.tag }}
