name: Windows

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**/*.md'
  pull_request:
    branches: [ main ]

jobs:
  windows:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - uses: actions/cache@v3
      name: Cache NuGet
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Build
      run: dotnet build
