name: Windows

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**/*.md'
  pull_request:
    branches: [ main ]

jobs:
  windows:
    name: Build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        framework: ['net462', 'net48', 'netcoreapp3.1', 'net5.0', 'net6.0']
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - uses: actions/cache@v3
      name: Cache NuGet
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Build
      run: dotnet build --framework ${{ matrix.framework }}
